window.GAME_CONFIG = {
  terrainPalette: {
    grass: ["#1e4131", "#2b5642", "#3a6953"],
    sand: ["#6b5633", "#806744", "#987b55"],
    stone: ["#46525a", "#57646d", "#69767f"],
    water: ["#18394e", "#244d66", "#2f617c"],
  },
  xpOrbValues: [1, 2, 3, 5, 8, 13, 21, 34, 55],
  xpCurve: {
    base: 58,
    linear: 16,
    exponent: 1.61,
    exponentialScale: 8.4,
  },
  enemyScaling: {
    startMinute: 2,
    regularLinear: 0.022,
    regularQuadratic: 0.0015,
    bossLinear: 0.022,
    bossQuadratic: 0.0013,
    bossEncounterBonus: 0.06,
  },
  majorUpgrades: {
    pairWeights: {
      barrage: 1.06,
      dash: 1.02,
      shape: 1,
      survival: 0.94,
      control: 0.98,
      stance: 0.96,
    },
    repeatPairWeight: 0.42,
    fatiguePerPairPick: 0.14,
    ranks: {
      "split-volley": [
        { projectiles: 1, projectileSpeed: 48 },
        { projectiles: 1, projectileSpeed: 40 },
        { projectiles: 1, projectileSpeed: 34 },
        { projectiles: 1, projectileSpeed: 28 },
        { projectiles: 1, projectileSpeed: 22 },
      ],
      "arcane-focus": [
        { autoDamageMultiplier: 0.22, bossDamageBonus: 0.18 },
        { autoDamageMultiplier: 0.17, bossDamageBonus: 0.14 },
        { autoDamageMultiplier: 0.13, bossDamageBonus: 0.11 },
        { autoDamageMultiplier: 0.1, bossDamageBonus: 0.09 },
        { autoDamageMultiplier: 0.08, bossDamageBonus: 0.07 },
      ],
      reservoir: [
        { dashCharges: 1 },
        { dashCharges: 1 },
        { dashCharges: 1 },
        { dashCharges: 1 },
        { rechargeMultiplier: 0.18, invulnDuration: 0.02, restoreCharge: 1 },
      ],
      surge: [
        { rechargeMultiplier: 0.28, haste: 0.16 },
        { rechargeMultiplier: 0.22, haste: 0.13 },
        { rechargeMultiplier: 0.18, haste: 0.11 },
        { rechargeMultiplier: 0.14, haste: 0.09 },
        { rechargeMultiplier: 0.11, haste: 0.07 },
      ],
      "wide-reach": [
        { area: 0.24, duration: 0.12 },
        { area: 0.18, duration: 0.09 },
        { area: 0.14, duration: 0.07 },
        { area: 0.11, duration: 0.06 },
        { area: 0.09, duration: 0.05 },
      ],
      "needle-casting": [
        { autoDamageMultiplier: 0.18, skillDamageBonus: 0.16, projectileSpeed: 44 },
        { autoDamageMultiplier: 0.14, skillDamageBonus: 0.12, projectileSpeed: 34 },
        { autoDamageMultiplier: 0.11, skillDamageBonus: 0.09, projectileSpeed: 28 },
        { autoDamageMultiplier: 0.09, skillDamageBonus: 0.07, projectileSpeed: 24 },
        { autoDamageMultiplier: 0.07, skillDamageBonus: 0.06, projectileSpeed: 20 },
      ],
      "vital-reserve": [
        { maxHp: 38, healNow: 30, damageReduction: 0.1, healAmp: 0.24 },
        { maxHp: 30, healNow: 24, damageReduction: 0.08, healAmp: 0.18 },
        { maxHp: 24, healNow: 18, damageReduction: 0.06, healAmp: 0.14 },
        { maxHp: 18, healNow: 14, damageReduction: 0.05, healAmp: 0.12 },
        { maxHp: 14, healNow: 10, damageReduction: 0.04, healAmp: 0.1 },
      ],
      overclock: [
        { fireIntervalFactor: 0.82, skillCooldownRecovery: 0.2 },
        { fireIntervalFactor: 0.86, skillCooldownRecovery: 0.16 },
        { fireIntervalFactor: 0.89, skillCooldownRecovery: 0.13 },
        { fireIntervalFactor: 0.91, skillCooldownRecovery: 0.11 },
        { fireIntervalFactor: 0.93, skillCooldownRecovery: 0.09 },
      ],
      lockdown: [
        { statusPotency: 0.18, statusDuration: 0.18 },
        { statusPotency: 0.14, statusDuration: 0.14 },
        { statusPotency: 0.11, statusDuration: 0.11 },
        { statusPotency: 0.09, statusDuration: 0.09 },
        { statusPotency: 0.08, statusDuration: 0.08 },
      ],
      execution: [
        { damageVsAfflicted: 0.22 },
        { damageVsAfflicted: 0.17 },
        { damageVsAfflicted: 0.14 },
        { damageVsAfflicted: 0.11 },
        { damageVsAfflicted: 0.09 },
      ],
      fieldcraft: [
        { zoneDamage: 0.2, duration: 0.16 },
        { zoneDamage: 0.16, duration: 0.12 },
        { zoneDamage: 0.13, duration: 0.09 },
        { zoneDamage: 0.1, duration: 0.07 },
        { zoneDamage: 0.08, duration: 0.06 },
      ],
      pursuit: [
        { speedMultiplier: 0.16, dashDistance: 24, afterDashPower: 0.14 },
        { speedMultiplier: 0.12, dashDistance: 18, afterDashPower: 0.11 },
        { speedMultiplier: 0.09, dashDistance: 14, afterDashPower: 0.09 },
        { speedMultiplier: 0.07, dashDistance: 10, afterDashPower: 0.07 },
        { speedMultiplier: 0.06, dashDistance: 8, afterDashPower: 0.06 },
      ],
    },
  },
  spawnDirector: {
    baseInterval: 1.08,
    minInterval: 0.17,
    maxEnemiesOnField: 420,
    bossSpawnIntervalMultiplier: 5.8,
    bossAmbientCap: 10,
  },
  spawnRoster: [
    {
      type: "grunt",
      unlockTime: 0,
      cap: null,
      weightBase: 0.82,
      weightPressureDelta: -0.16,
      countBase: 1,
      countChances: [0.44, 0.14],
      countPressureDeltas: [0.18, 0.1],
    },
    {
      type: "tank",
      unlockTime: 0,
      cap: null,
      weightBase: 0.16,
      weightPressureDelta: 0.14,
      countFixed: 1,
    },
    {
      type: "runner",
      unlockTime: 0,
      cap: null,
      weightBase: 0.28,
      weightPressureDelta: 0.16,
      countBase: 2,
      countChances: [0.62, 0.24],
      countPressureDeltas: [0.18, 0.12],
    },
    {
      type: "hexer",
      unlockTime: 45,
      cap: 8,
      weightBase: 0.18,
      weightPressureDelta: 0.16,
      countThresholds: [{ chance: 0.28, amount: 2 }],
    },
    {
      type: "fang",
      unlockTime: 95,
      cap: 6,
      weightBase: 0.14,
      weightPressureDelta: 0.14,
      countThresholds: [{ chance: 0.35, amount: 2 }],
    },
    {
      type: "wraith",
      unlockTime: 165,
      cap: 5,
      weightBase: 0.1,
      weightPressureDelta: 0.12,
      countFixed: 1,
    },
    {
      type: "oracle",
      unlockTime: 220,
      cap: 6,
      weightBase: 0.08,
      weightPressureDelta: 0.12,
      countFixed: 1,
    },
    {
      type: "brood",
      unlockTime: 250,
      cap: 5,
      weightBase: 0.08,
      weightPressureDelta: 0.12,
      countThresholds: [{ chance: 0.3, amount: 2 }],
    },
    {
      type: "banner",
      unlockTime: 180,
      cap: 4,
      weightBase: 0.07,
      weightPressureDelta: 0.11,
      countFixed: 1,
    },
    {
      type: "mortar",
      unlockTime: 290,
      cap: 4,
      weightBase: 0.06,
      weightPressureDelta: 0.12,
      countThresholds: [{ chance: 0.22, amount: 2 }],
    },
    {
      type: "bulwark",
      unlockTime: 350,
      cap: 4,
      weightBase: 0.05,
      weightPressureDelta: 0.13,
      countFixed: 1,
    },
  ],
  bossGapRanges: [
    { min: 112, max: 132 },
    { min: 120, max: 146 },
    { min: 132, max: 160 },
    { min: 146, max: 178 },
    { min: 160, max: 194 },
    { min: 170, max: 208 },
  ],
  bossUnlockTimes: {
    countess: 0,
    colossus: 120,
    abyss: 250,
    matriarch: 430,
    harbinger: 320,
    regent: 520,
  },
  bossRandomWeights: {
    countess: 4.6,
    colossus: 4.1,
    abyss: 3.3,
    matriarch: 2.7,
    harbinger: 2.9,
    regent: 2.2,
  },
  classUnlockRequirements: {
    wind: { xp: 0, enemyType: null, enemyKills: 0 },
    frost: { xp: 1500, enemyType: "runner", enemyKills: 70 },
    fire: { xp: 4200, enemyType: "tank", enemyKills: 75 },
    necro: { xp: 7800, enemyType: "brood", enemyKills: 40 },
    blood: { xp: 12500, enemyType: "fang", enemyKills: 70 },
  },
  enemyArchetypes: {
    grunt: {
      emoji: "\uD83E\uDDDF",
      radius: 16,
      speed: 76,
      hp: 30,
      touchDamage: 11,
      reward: 1,
      xp: 8,
      font: '31px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
    },
    tank: {
      emoji: "\uD83E\uDDCC",
      radius: 23,
      speed: 48,
      hp: 78,
      touchDamage: 19,
      reward: 3,
      xp: 20,
      font: '40px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
    },
    runner: {
      emoji: "\uD83E\uDD87",
      radius: 13,
      speed: 126,
      hp: 22,
      touchDamage: 8,
      reward: 2,
      xp: 9,
      font: '25px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
    },
    hexer: {
      emoji: "\uD83E\uDDDB",
      radius: 17,
      speed: 68,
      hp: 42,
      touchDamage: 10,
      reward: 4,
      xp: 16,
      font: '31px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 45,
    },
    fang: {
      emoji: "\uD83D\uDC3A",
      radius: 20,
      speed: 82,
      hp: 58,
      touchDamage: 15,
      reward: 5,
      xp: 19,
      font: '34px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 95,
    },
    wraith: {
      emoji: "\uD83D\uDC7B",
      radius: 21,
      speed: 74,
      hp: 72,
      touchDamage: 13,
      reward: 6,
      xp: 24,
      flying: true,
      font: '31px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 165,
    },
    oracle: {
      emoji: "\uD83D\uDD2E",
      radius: 24,
      speed: 64,
      hp: 88,
      touchDamage: 12,
      reward: 7,
      xp: 30,
      font: '34px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 220,
    },
    brood: {
      emoji: "\uD83D\uDD77",
      radius: 28,
      speed: 62,
      hp: 122,
      touchDamage: 18,
      reward: 8,
      xp: 38,
      font: '42px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 250,
    },
    banner: {
      emoji: "\uD83C\uDFBA",
      radius: 20,
      speed: 58,
      hp: 102,
      touchDamage: 10,
      reward: 8,
      xp: 36,
      font: '34px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 180,
    },
    mortar: {
      emoji: "\uD83D\uDCE1",
      radius: 22,
      speed: 55,
      hp: 108,
      touchDamage: 12,
      reward: 9,
      xp: 42,
      font: '34px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 290,
    },
    bulwark: {
      emoji: "\uD83D\uDEE1\uFE0F",
      radius: 26,
      speed: 44,
      hp: 168,
      touchDamage: 22,
      reward: 11,
      xp: 56,
      font: '40px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      unlockTime: 360,
    },
    countess: {
      emoji: "\uD83E\uDD87",
      radius: 42,
      speed: 92,
      hp: 2450,
      touchDamage: 36,
      reward: 110,
      xp: 280,
      flying: true,
      font: '90px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      isBoss: true,
      name: "Crimson Countess",
    },
    colossus: {
      emoji: "\uD83D\uDDFF",
      radius: 52,
      speed: 54,
      hp: 8200,
      touchDamage: 46,
      reward: 190,
      xp: 430,
      font: '108px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      isBoss: true,
      name: "Grave Colossus",
    },
    abyss: {
      emoji: "\uD83D\uDC41",
      radius: 58,
      speed: 78,
      hp: 5300,
      touchDamage: 42,
      reward: 240,
      xp: 520,
      flying: true,
      font: '96px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      isBoss: true,
      name: "Abyss Eye",
    },
    matriarch: {
      emoji: "\uD83D\uDD77",
      radius: 64,
      speed: 62,
      hp: 4800,
      touchDamage: 50,
      reward: 280,
      xp: 640,
      font: '112px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      isBoss: true,
      name: "Brood Matriarch",
    },
    harbinger: {
      emoji: "\uD83E\uDDFF",
      radius: 60,
      speed: 86,
      hp: 6300,
      touchDamage: 44,
      reward: 320,
      xp: 760,
      flying: true,
      font: '102px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      isBoss: true,
      name: "Void Harbinger",
    },
    regent: {
      emoji: "\uD83E\uDE90",
      radius: 68,
      speed: 72,
      hp: 7200,
      touchDamage: 52,
      reward: 380,
      xp: 920,
      flying: true,
      font: '110px "Segoe UI Emoji", "Apple Color Emoji", "Noto Color Emoji", sans-serif',
      isBoss: true,
      name: "Starfall Regent",
    },
  },
  classDefs: {
    wind: {
      id: "wind",
      icon: "\uD83C\uDF2C\uFE0F",
      playerEmoji: "\uD83E\uDDDD\uD83C\uDFFB\u200D\u2642\uFE0F",
      title: "Wind Mage",
      adjective: "Wind",
      description: "Fast mobility-control mage that reroutes pressure, opens escape paths, and survives by movement more than damage.",
      color: "#e8f5ff",
      projectileColor: "#d7f6ff",
      projectileRgb: "215, 246, 255",
      autoDamage: 18,
      speedMultiplier: 1.22,
      maxHpMultiplier: 0.98,
      passiveLabel: "Slipstream Force",
      passiveText: "Auto attacks strongly displace enemies. Wind skills disperse hostile projectiles and trigger short slipstream speed bursts.",
      passiveType: "wind",
      skillUnlocks: [5, 15, 25],
      unlockMessage: "Learned a new wind technique.",
      skills: [
        { id: "gale-ring", title: "Gale Ring", icon: "\uD83C\uDF00", slot: 1, cooldown: 7.2, role: "Panic", targeting: "self" },
        { id: "crosswind-strip", title: "Crosswind Strip", icon: "\uD83D\uDCA8", slot: 2, cooldown: 10.8, role: "Zone", targeting: "movement" },
        { id: "tempest-node", title: "Tempest Node", icon: "\uD83C\uDF2A\uFE0F", slot: 3, cooldown: 15.5, role: "Signature", targeting: "cluster" },
      ],
    },
    frost: {
      id: "frost",
      icon: "\u2744\uFE0F",
      playerEmoji: "\uD83E\uDDD9\uD83C\uDFFB\u200D\u2642\uFE0F",
      title: "Frost Mage",
      adjective: "Frost",
      description: "Crit-control mage that stacks Chill, creates Brittle windows, and cashes them out with precise execution hits.",
      color: "#8ed8ff",
      projectileColor: "#9fe2ff",
      projectileRgb: "159, 226, 255",
      autoDamage: 23,
      speedMultiplier: 1,
      maxHpMultiplier: 1,
      passiveLabel: "Cold Equation",
      passiveText: "Auto attacks stack Chill aggressively. Controlled enemies become vulnerable to critical hits, and Brittle targets are clean execution windows.",
      passiveType: "frost",
      skillUnlocks: [5, 15, 25],
      unlockMessage: "Learned a new frost technique.",
      skills: [
        { id: "blizzard-wake", title: "Blizzard Wake", icon: "\uD83C\uDF28\uFE0F", slot: 1, cooldown: 7.6, role: "Panic", targeting: "self" },
        { id: "permafrost-seal", title: "Permafrost Seal", icon: "\u2746", slot: 2, cooldown: 11.8, role: "Zone", targeting: "cluster" },
        { id: "crystal-spear", title: "Crystal Spear", icon: "\uD83D\uDD37", slot: 3, cooldown: 13.8, role: "Signature", targeting: "threat" },
      ],
    },
    fire: {
      id: "fire",
      icon: "\uD83D\uDD25",
      playerEmoji: "\uD83E\uDEC5\uD83C\uDFFB",
      title: "Fire Mage",
      adjective: "Fire",
      description: "AoE damage mage that stacks Burn quickly and incinerates clustered enemies faster than any other class.",
      color: "#ffb25e",
      projectileColor: "#ffc16b",
      projectileRgb: "255, 193, 107",
      autoDamage: 23,
      speedMultiplier: 1,
      maxHpMultiplier: 0.96,
      passiveLabel: "Kindling",
      passiveText: "Auto attacks add Burn stacks. Fire zones build stacks quickly, and burning deaths spread the blaze.",
      passiveType: "fire",
      skillUnlocks: [5, 15, 25],
      unlockMessage: "Learned a new fire technique.",
      skills: [
        { id: "cinder-halo", title: "Cinder Halo", icon: "\u2604\uFE0F", slot: 1, cooldown: 7.5, role: "Panic", targeting: "self" },
        { id: "sunspot", title: "Sunspot", icon: "\uD83C\uDF1E", slot: 2, cooldown: 11.2, role: "Zone", targeting: "cluster" },
        { id: "ash-comet", title: "Ash Comet", icon: "\u2604", slot: 3, cooldown: 14.6, role: "Signature", targeting: "cluster" },
      ],
    },
    necro: {
      id: "necro",
      icon: "\uD83D\uDC80",
      playerEmoji: "\uD83E\uDDDD\uD83C\uDFFF",
      title: "Necromancer",
      adjective: "Necrotic",
      description: "Fragile summoner that owns space through swarm uptime, piercing marks, and a much denser procession of green summons.",
      color: "#7de0b5",
      projectileColor: "#8cf0c3",
      projectileRgb: "140, 240, 195",
      autoDamage: 15,
      speedMultiplier: 1,
      maxHpMultiplier: 0.78,
      passiveLabel: "Black Procession",
      passiveText: "Auto attacks pierce and mark enemies. Marked kills and necrotic skills call additional Thralls, and your summon cap is increased.",
      passiveType: "necro",
      skillUnlocks: [5, 15, 25],
      unlockMessage: "Learned a new necrotic rite.",
      skills: [
        { id: "bone-ward", title: "Bone Ward", icon: "\uD83E\uDDB4", slot: 1, cooldown: 8.2, role: "Panic", targeting: "self" },
        { id: "requiem-field", title: "Requiem Field", icon: "\uD83E\uDEA6", slot: 2, cooldown: 12.2, role: "Zone", targeting: "cluster" },
        { id: "grave-call", title: "Grave Call", icon: "\u26B0\uFE0F", slot: 3, cooldown: 16.4, role: "Signature", targeting: "cluster" },
      ],
    },
    blood: {
      id: "blood",
      icon: "\uD83E\uDE78",
      playerEmoji: "\uD83E\uDDDB\uD83C\uDFFB",
      title: "Blood Mage",
      adjective: "Blood",
      description: "Blood bruiser that holds ground, drains life in close combat, and turns commitment into durability instead of crit spikes.",
      color: "#ff6a88",
      projectileColor: "#ff7b98",
      projectileRgb: "255, 123, 152",
      autoDamage: 23,
      speedMultiplier: 0.95,
      maxHpMultiplier: 1.42,
      passiveLabel: "Hemomancy",
      passiveText: "Auto attacks drain life. Blood-marked enemies feed your sustain, and blood magic hardens you while you hold your ground.",
      passiveType: "blood",
      skillUnlocks: [5, 15, 25],
      unlockMessage: "Learned a new blood rite.",
      skills: [
        { id: "vein-burst", title: "Vein Burst", icon: "\uD83D\uDCA5", slot: 1, cooldown: 7.1, role: "Panic", targeting: "self" },
        { id: "crimson-pool", title: "Crimson Pool", icon: "\uD83E\uDE78", slot: 2, cooldown: 11.4, role: "Zone", targeting: "self" },
        { id: "blood-rite", title: "Blood Rite", icon: "\uD83E\uDDEA", slot: 3, cooldown: 15.2, role: "Signature", targeting: "self" },
      ],
    },
  },
};
